### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/firmware-manager#1]
Integrate automatic firmware updates into Pop!_OS via a system library that displays in gcc (Devices > Firmware) and daemon that checks for updates and provides notifications. The library and daemon can be installed on other distributions for system76 firmware updates. Both will be installed for system76 customers using Ubuntu probably with the system76-driver package.

![Firmware-panel-no-managed-devices](https://user-images.githubusercontent.com/3430283/59790349-fed59e00-928c-11e9-9831-765abe539c98.png)

"System Firmware" is firmware that requires a reboot to install.

![Firmware-panel](https://user-images.githubusercontent.com/3430283/59790353-01d08e80-928d-11e9-841c-fd677e669de7.png)

![System and device firmware update clicked](https://user-images.githubusercontent.com/3430283/59790360-0432e880-928d-11e9-9f72-2e880e58e69a.png)

**Comment by mmstick** [comment]
Tracking progress:

- [x] system76-firmware client in Rust
  - [ ] changes are merged into the system76-firmware repo
- [ ] GTK library
  - [x] Rust library is written
  - [ ] C bindings to the library is written
  - [ ] Firmware update dialog is written
  - [ ] Integration in GNOME Software
- [x] GTK application in Rust based on the library

**Comment by mmstick** [comment]
The new firmware widget library is working in Rust now. Any errors reported by the firmware client accessing the firmware daemon are also being handled and directed to an info bar in the widget.

![Screenshot from 2019-06-24 15-08-30](https://user-images.githubusercontent.com/4143535/60052245-fa94f080-9691-11e9-8101-57dcd88c4a1f.png)

![Screenshot from 2019-06-24 15-09-30](https://user-images.githubusercontent.com/4143535/60052296-1e583680-9692-11e9-84de-8eea6bfbc1d5.png)

**Comment by WatchMkr** [comment]
Looks good! Check with @isantop on the dialog box icon. We have a Pop firmware icon for that image.

**Comment by mmstick** [comment]
The C bindings are complete, with a [working example](https://github.com/pop-os/firmware-manager/tree/master/ffi/examples/c), so now I'll begin working on integration into GNOME Settings.

**Comment by mmstick** [comment]
:rocket: The firmware panel in GNOME Settings worked on the first try.

![Screenshot from 2019-06-25 14-54-19](https://user-images.githubusercontent.com/4143535/60132626-20d19380-9759-11e9-9051-5af440b21a8f.png)

**Comment by mmstick** [comment]
Screenshot when the firmware daemon service is not active, and thus firmware scanning is deactive.

![Screenshot from 2019-06-25 17-26-59](https://user-images.githubusercontent.com/4143535/60140296-7a908880-976e-11e9-9dbe-0ffc27057149.png)
