### ISSUE TITLE
Unavailable firmware message should only appear after searching for firmware

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#10]
When switching from a different settings tab to the Firmware tab, very briefly the "Managed Firmware Unavailable: No devices supporting automatic firmware updates detected" is shown. As it only appears for a brief moment, it appears jarring (not to mention incorrect). Perhaps wait to show that message until making an attempt to look for supported firmware first?

**Comment by brs17** [comment]
Video demo of issue:

![video_demo](https://user-images.githubusercontent.com/7460774/61803909-3b4a6b80-adf0-11e9-982e-ab54447e10db.gif)

**Comment by mmstick** [comment]
I'll hide the view until the scan method is complete, and then show one or the other.
