### ISSUE TITLE
Error reading changelog of thelio-major-r1

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#11]
An error is thrown when attempting to read the system firmware for thelio-major-r1
![error_reading_changelog](https://user-images.githubusercontent.com/7460774/61809345-5621dd80-adfa-11e9-8433-dd776d742632.png)

Potentially related to the fact that these values can be optional: https://github.com/pop-os/system76-firmware/blob/b74e9f8db115fdfd6495be7a3695d84bfa8b746b/daemon/src/lib.rs#L200

**Comment by mmstick** [comment]
It should be working with the latest commit. Will need to test to confirm.
