### ISSUE TITLE
Discussion point: How frequent should the user be notified of available firmware?

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#13]

**Comment by WatchMkr** [comment]
Firmware often includes security fixes. We should check for updates daily and notify whenever they're available.

Because th firmware device list is small and updates infrequent, it is unlikely we'll frustrate users with too many notifications.

**Comment by mmstick** [comment]
We would need to determine which application starts the notify application, since it only runs long enough to check for updates before exiting. Or if it should be its own user service.

**Comment by WatchMkr** [comment]
Seems that `firmware-manager-notify` is a natural fit. What do you think though?

**Comment by mmstick** [comment]
`firmware-manager-notify` is executed by the login service at startup, but it exits as soon as soon as it is clicked. We would need to either have an existing background service occasionally launch the notify application to check for updates, or we would keep it running in the background permanently, to occasionally check for updates itself.

**Comment by mmstick** [comment]
I think I'll do this by adding a systemd user timer to the notify package, and have that set to rerun the notification binary every day.

**Comment by mmstick** [comment]
This should be working now.
