### ISSUE TITLE
darp5: Opening firmware tab in Gnome Settings has poorly alligned content

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#16]
On the Darter Pro, when selecting the Firmware tab, the sections are formatted incorrectly (not wide enough)

Not good:
 ![Screenshot from 2019-07-29 09-41-09](https://user-images.githubusercontent.com/7460774/62062228-d626b980-b1e5-11e9-8bee-ee7dd058c534.png)

Good:
![Screenshot from 2019-07-29 09-26-51](https://user-images.githubusercontent.com/7460774/62062502-5816e280-b1e6-11e9-8567-02e09898643e.png)

I am unable to recreate this issue with the same result on thelio-r1 but when the page is loading initially I do see the page, for a moment, is formatted similarly before resizing and fixing itself.
![bug](https://user-images.githubusercontent.com/7460774/62063755-be9d0000-b1e8-11e9-86ae-fa26f5ae9303.gif)

**Comment by mmstick** [comment]
I found the workaround. I'm dynamically sizing the view's content container based on the width of the entire view's container. However, the initial value for a widget's `size_allocation` is `(0, 0)`, so I need to hide the content until the value is not 0, and add a signal to check the actual width of the view once it has been realized.
