### ISSUE TITLE
Firmware changelog needs to be better formatted

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#18]
Kate will provide guidance in how to best format the firmware changelog as seen below:
![Screenshot from 2019-07-31 08-32-52](https://user-images.githubusercontent.com/7460774/62222274-524d0880-b370-11e9-9c6e-376b1654cb6b.png)

**Comment by WatchMkr** [comment]
Reviewed w/ Kate: Hierarchy Update

![IMG_2926](https://user-images.githubusercontent.com/3430283/62228509-05226400-b37b-11e9-8809-1926969ac88d.JPG)

**Comment by brs17** [comment]
The dropdown notification looks good.

This is what the layout and changelog currently looks like.
![Screenshot from 2019-08-01 15-39-08](https://user-images.githubusercontent.com/7460774/62330130-fa4bfa00-b474-11e9-9573-4988ae6a08b3.png)

 I think there's still a few changes that we want to include before we're ready to ship. 
 - The mockup includes a <b>Changelog</b> title as the first text in the expanded dropdown.
 - Separators should be between changelog entries not after the version provided in a specific entry.

**Comment by mmstick** [comment]
Updated look

![Screenshot from 2019-08-01 17-10-49](https://user-images.githubusercontent.com/4143535/62333128-7ea37a80-b47f-11e9-964b-e6b31eef20ed.png)

**Comment by mmstick** [comment]
Updated look

![Screenshot from 2019-08-01 17-22-21](https://user-images.githubusercontent.com/4143535/62333501-f1f9bc00-b480-11e9-9c6f-2b6c4764f8e3.png)
