### ISSUE TITLE
Multiple thelio-io boards only show one `Update` button

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#19]
On systems with multiple thelio-io boards, there is only one `Update` button provided. If a separate update button cannot be provided for each board, potentially both boards should be listed as one device.

![Screenshot from 2019-07-31 08-09-37](https://user-images.githubusercontent.com/7460774/62222350-6d1f7d00-b370-11e9-898d-0807ee44f449.png)

**Comment by mmstick** [comment]
The reason for multiple to display is because they may have different versions of firmware installed, theoretically.

**Comment by WatchMkr** [comment]
We discussed and decided to collapse multiple boards to one entry and show the oldest firmware version. Updating always installs on all Thelio Io boards.
