### ISSUE TITLE
Transition from system76-driver's firmware UI

### ISSUE THREAD

**Issue by jackpot51** [pop-os/firmware-manager#2]
- [x] Release fwupd with privacy concerns addressed (@jackpot51)
- [x] Release firmware-manager, but do not depend on it yet (@mmstick)
  - [x] Add autostart file to show notifications by running firmware-manager in the background without a UI
  - [x] The notification should launch the gnome-control-center firmware pane if the desktop file for it can be found, and launch the firmware-manager application otherwise
- [x] Perform testing on firmware-manager (@brs17)
  - [x] Find a way to roll back or simulate fwupd updates
  - [x] Test update notifications
  - [x] Test use in Ubuntu or alternative Desktop Environments
- [x] Prepare a branch of gnome-control-center with the following (@mmstick):
  - [x] Firmware pane that shows up in GNOME Shell
  - [x] Hide firmware-manager from GNOME Shell, potentially by using dpkg-divert or NoDisplay=True if and only if gnome-control-center with a Firmware pane is installed
- [x] Prepare a branch of system76-driver with the following (@jackpot51):
  - [x] Depends on firmware-manager
  - [x] Remove system76-firmware tool
  - [x] Remove desktop file and autostart

**Comment by mmstick** [comment]
Currently, the firmware-manager application & desktop file is in its own package, separate from the GTK lib package which GNOME Control Center uses. So, Pop!_OS could depend on the lib with the patched GNOME Settings, and then Ubuntu would install the `firmware-manager` package which provides the standalone application.

**Comment by mmstick** [comment]
> Find a way to roll back or simulate fwupd updates

I added a [TESTING.md](https://github.com/pop-os/firmware-manager/blob/master/TESTING.md#downgrading-fwupd-managed-firmware) which shows how to do this.

**Comment by mmstick** [comment]
Firmware manager is now ready to release, as soon as the updated `fwupd` package is released, and the debian packages for this are built.

- The `firmware-manager-notify` package contains the autostart file, and notification binary. This can be added as a depends for Ubuntu and Pop!_O. It will attempt to exec `gnome-control-center firmware` if `/usr/share/applications/gnome-firmware-panel.desktop` is found, else the standalone application.
- The `firmware-manager` package contains the standalone GTK application and its desktop file.
- The `libfirmware-manager` package provides the GTK widget library used as a depends by GNOME Settings
