### ISSUE TITLE
Missing visual indication of changelog content

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#20]
Currently there is no indication that selecting a device will show the firmware changelog. Using a dropdown button similar to the one on the `Color` tab would probably be a good fix. The current thought is that such a button should be on the far left of each device.

**Comment by mmstick** [comment]
Should the icon be on the right of the device boxes, or the left?

**Comment by brs17** [comment]
Left side as seen on the Device firmware part of the mockup here: https://github.com/pop-os/firmware-manager/issues/18#issuecomment-516915864
