### ISSUE TITLE
System firmware does not need a progress bar

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#21]
With system firmware already downloaded before notifying the user of new firmware, the progress bar shown after selecting reboot shows up for a split second providing no real value to the user.

This progress bar c/should probably just be removed from system firmware updates.

**Comment by mmstick** [comment]
Should we still display a progress bar when a device is being flashed, and system firmware is then clicked to schedule an update in the queue? Currently, devices are being flashed serially, so firmware will wait in line for their turn to be processed.

**Comment by brs17** [comment]
Per discussion in person, we decided we will keep the progress bar but change the wording to "Waiting". With that change and fixing https://github.com/pop-os/firmware-manager/issues/22 it will look good. 

The reason for the progress bar is for queuing multiple firmware updates (and preventing a reboot in the middle of a device firmware update).

**Comment by mmstick** [comment]
That reminds me that we should activate a lock/suspend/reboot/shutdown inhibitor

**Comment by brs17** [comment]
I think we're 90% there. I'm thinking we don't need the progress bar underneath `Waiting` as that progress bar never really progresses as once waiting is over the system reboots.

![Screenshot from 2019-08-02 08-14-23](https://user-images.githubusercontent.com/7460774/62376884-ea78f800-b4fe-11e9-9361-f6b580c76513.png)
