### ISSUE TITLE
Update button looks slightly cut-off on the bottom

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#25]
The bottom of the `Update` button/the shadow below it appears to be cut off.

![Screenshot from 2019-07-31 08-09-37](https://user-images.githubusercontent.com/7460774/62226898-2cc3fd00-b378-11e9-93ec-930bf9e52414.png)

![rect45](https://user-images.githubusercontent.com/7460774/62228778-95f93f80-b37b-11e9-8f19-484a049692f4.png)

**Comment by mmstick** [comment]
Seems to be a limitation in GTK that doesn't handle shadows very well, so they get clipped at the widget boundaries. Needs a 15 point margin around the button so that the shadow isn't clipped on hover.
