### ISSUE TITLE
Ensure operability between firmware-manager and GNOME Software

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#26]
This has not been tested yet, but we'll want to ensure good behavior between fwupd firmware updates/notifications from the firmware-manager and GNOME Software.

**Comment by WatchMkr** [comment]
Add build flag to disable firmware-manager fwupd updates for Ubuntu.

**Comment by mmstick** [comment]
Luckily I foresaw this in advance, and both `system76-firmware` and `fwupd` are conditional compilation features. However, I just noticed that the flags aren't working right. Will fix that now.

**Comment by mmstick** [comment]
An Ubuntu-specific branch can now use `make features=system76` to build everything with system76-support only, whereas packaging for Pop!_OS can use `make features='fwupd system76'` to build for both.

**Comment by jackpot51** [comment]
@mmstick we could set some environmental variable when doing CI builds of packages for Ubuntu - i.e. when --dev is passed to the ci script.

**Comment by jackpot51** [comment]
Then use that variable to determine the default features

**Comment by mmstick** [comment]
I've added a `S76_DEV` variable to the makefile. If it is set to `1` it will default to `system76`, otherwise `fwupd system76`.

**Comment by WatchMkr** [comment]
At the moment, fwupd devices are visible in firmware-manager in Ubuntu 18.04. However, this is okay because it appears fwupd updates are not showing up in Ubuntu Software on 18.04.
