### ISSUE TITLE
System firmware popup misaligned

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#27]
I believe due to the fix for: https://github.com/pop-os/firmware-manager/issues/23

the popup now looks like this:

![Screenshot from 2019-08-01 12-13-03](https://user-images.githubusercontent.com/7460774/62317074-19875f00-b456-11e9-9379-c4278f1a3ffe.png)

**Comment by mmstick** [comment]
You're right, it's not being added to the same container.
