### ISSUE TITLE
Firmware-manager icon missing in Ubuntu 18.04

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#35]
Firmware-manager icon is missing in Ubuntu 18.04
![Screenshot from 2019-08-14 11-16-18](https://user-images.githubusercontent.com/7460774/63041598-78e96400-be85-11e9-8365-4317c517246e.png)

**Comment by mmstick** [comment]
We may need to include the icon with the package, as it's only part of the Pop icon theme on Pop.
