### ISSUE TITLE
Phrasing of system upgrade pop-up is strange

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#38]
Currently the pop-up for system firmware notifications says: `Fixes and features include:`  and then lists the changelog. Potentially that is a little odd, as showing the changelog of versions prior to what is installed isn't really showing what fixes and features are included in the update. 

![Screenshot from 2019-08-16 08-24-59](https://user-images.githubusercontent.com/7460774/63174599-862a5e00-bfff-11e9-90bb-757ca78dcec0.png)

Maybe change the wording to just state that the following is a changelog? Or show only the changelog containing the latest update?

**Comment by WatchMkr** [comment]
I agree. Let’s remove that line entirely and match the new change log design on the main panel.

**Comment by mmstick** [comment]
Like so, or should we have the padding for dialogs?

![Screenshot from 2019-08-16 10-48-16](https://user-images.githubusercontent.com/4143535/63183900-5edd8c00-c013-11e9-8023-7fa322f3d1d5.png)

**Comment by brs17** [comment]
Keep "Firmware version $version is available." above *Changelog*.
