### ISSUE TITLE
fwupd devices not showing up in firmware tab in GNOME control center (19.04)

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#39]
In Pop!_OS 19.04, fwupd devices are not showing up in GNOME control center.

**Comment by brs17** [comment]
Issue currently only seems to be happening on one oryp5.

**Comment by brs17** [comment]
This seems to be reproduced when the fwupd device is plugged in on cold boot or reboot (but not on logout/login).

**Comment by mmstick** [comment]
This happens every time on the first boot?

**Comment by WatchMkr** [comment]
This bug is difficult to reliably reproduce. Lower-priority.

**Comment by mmstick** [comment]
We might be able to get some useful information from running `sudo busctl monitor` while reloading the panel.

**Comment by WatchMkr** [comment]
I think this has been resolved with USB hotplugging. Re-open if we see it again.
