### ISSUE TITLE
System firmware should list product name and not model number

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#40]

**Comment by mmstick** [comment]
Implemented by https://github.com/pop-os/firmware-manager/commit/8e78b11f19e27ba004af1fa5c7e34f9afc139002

**Comment by brs17** [comment]
A few additional changes desired: https://github.com/pop-os/firmware-manager/commit/8e78b11f19e27ba004af1fa5c7e34f9afc139002#commitcomment-34721473
