### ISSUE TITLE
Pop!_OS 18.04 does not have firmware-manager integration in GNOME Control Center

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#41]
Pop!_OS 18.04 seems to behave identical to Ubuntu 18.04 where the firmware-manager application exists as a standalone program. All Pop!_OS distributions should have the firmware manager integrated into GNOME control center.

**Comment by mmstick** [comment]
`37cf2e33c` of gnome-control-center will build for bionic soon, for Pop.
