### ISSUE TITLE
Pop!_OS 18.04: Firmware icon missing on System firmware pop-up

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#44]
On Pop!_OS 18.04, the system firmware pop-up is missing the appropriate firmware icon

![Screenshot from 2019-08-16 14-30-56](https://user-images.githubusercontent.com/7460774/63196497-a8899f00-c032-11e9-846e-2d6261f9e9be.png)

**Comment by mmstick** [comment]
That's strange. The [firmware icons were added to the bionic branch of our icon theme](https://github.com/pop-os/icon-theme/commits/master_bionic).

**Comment by isantop** [comment]
@mmstick @brs17 Unless we're specifically overriding the Icon theme, that is correct. `application-x-firmware` in the bionic icon theme is symlinked to the generic binary file icon (which that is).

**Comment by isantop** [comment]
It's my vote that we not override the icon theme, and thus this is expected behavior.

**Comment by isantop** [comment]
It's pulling the correct icon. It's being overridden by the Pop overrides folder, which is where that change should have been made in the first place. 

The correction is in place as pop-os/icon-theme#48

**Comment by brs17** [comment]
Fixed, thank you @isantop !
