### ISSUE TITLE
Firmware update prompted for non-up-to-date version

### ISSUE THREAD

**Issue by miascugh** [pop-os/firmware-manager#45]
Hi, after installing the latest gnome control center update with the new firmware manager tab, it prompted me to update the thinkpad system firmware on my P50. This with a version older than the one I have installed already.
I suspect this has everything to do with the fact that I updated the firmware with Lenovo's tool on the Windows install of the machine and that wherever linux sources its firmware from hasn't caught up yet. But I suppose it might make sense to include a check whether a detected version mismatch is also more current.

![Screenshot from 2019-08-17 10-49-21](https://user-images.githubusercontent.com/98865/63209203-29ea3b80-c0de-11e9-9740-2fab4ca4da56.png)

**Comment by mmstick** [comment]
Sure, I will add the version check in a few minutes.
