### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by electrickite** [pop-os/firmware-manager#46]
Please consider adding release tags to this project. Now that it is a dependency of `system76-driver`, it would be helpful to package maintainers to have versioned releases.

**Comment by mmstick** [comment]
There is to be a 1.0 release soon.

**Comment by electrickite** [comment]
It looks like the `firmware-manager` PPA package is at version 0.1.0. Could the git repo be tagged with this version as well?

**Comment by mmstick** [comment]
The only issue with tags is they'll be out of date each time we push to production if we don't tag nearly-every commit.

**Comment by electrickite** [comment]
I’ll close this, since it seems like releases are being tagged now.

**Comment by electrickite** [comment]
Could a new tag be added for release 0.1.2?
