### ISSUE TITLE
Build from source not finding git repo?

### ISSUE THREAD

**Issue by rklrkl** [pop-os/firmware-manager#48]
I'm on CentOS 7 (Rust 1.36.0 which I think is recent enough) and after a Makefile tweak I mentioned in another issue (#47), I'm hitting a git access issue that stops the build immediately. I ran both:

make prefix=/usr features='fwupd system76'

and

make prefix=/usr features='fwupd'

(I don't have a System76 system, hence trying the second version as well) and both resulted in git access errors:

   Updating git repository `https://github.com/pop-os/system76-firmware`
   error: failed to load source for a dependency on `system76-firmware-daemon`

   Caused by:
   Unable to update https://github.com/pop-os/system76-firmware?branch=firmware-client#f77915c0

   Caused by:
    revspec 'f77915c0a3d23b7f4db0473e5956173fbecdc4eb' not found; class=Reference (4); code=NotFound (-3)

This is after checking out the source both with "git clone" and also just downloading the master zip file from Github and unpacking that. It appears that whatever git repo the build is expecting isn't there.

BTW, with the features='fwupd' build, why is it still trying to access the System76 code?

**Comment by mmstick** [comment]
Ah, that repository branch no longer exists. It needs to point to the master branch of system76-driver.

**Comment by mmstick** [comment]
> BTW, with the features='fwupd' build, why is it still trying to access the System76 code?

Vendoring still requires that the sources are fetched in case you do build the code later.
