### ISSUE TITLE
BIOS downgrade

### ISSUE THREAD

**Issue by saltyprogrammer** [pop-os/firmware-manager#51]
Issue:
The app suggests a BIOS downgrade from the latest version available from the provider (Dell).

System:
Dell G7 running Pop!_OS 19.04.

![firmware_app_issue](https://user-images.githubusercontent.com/44762437/63304525-f3145100-c2a8-11e9-866f-96c65e09c9ab.png)

**Comment by mmstick** [comment]
Duplicate of https://github.com/pop-os/firmware-manager/issues/45
