### ISSUE TITLE
UI flashes after updating Thelio IO firmware

### ISSUE THREAD

**Issue by leviport** [pop-os/firmware-manager#54]
After updating firmware for Thelio IO, the page refreshes a few times, which looks strange. It flashes the same way twice after updating a fwupd Logitech mouse receiver. I think it might be related to this commit: https://github.com/pop-os/firmware-manager/commit/eefb8c301cfbec019498367081c909f8005ca416

[peek-video.zip](https://github.com/pop-os/firmware-manager/files/3526354/peek-video.zip)

I had to zip my webm to upload it, but it shows the refreshing behavior.

**Comment by WatchMkr** [comment]
This is fixed in staging.
