### ISSUE TITLE
Unusable and confusing page when viewing from user without sudo permissions

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#57]
The following screenshot is what I get on a thelio-major-r1 logged in to a user without sudo permissions.

![Screenshot from 2019-08-26 08-22-42](https://user-images.githubusercontent.com/7460774/63700523-55f17500-c7e0-11e9-9a0a-aa49dcb19859.png)

This error is quite messy, and when attempting to dismiss the error the error reappears. This makes the page unusable with no real explanation for why it is not working.

As the firmware-manager is not usable without proper authentication, perhaps the user should be prompted to authenticate if they want to proceed on the firmware page? Thoughts? @jackpot51 , @WatchMkr, @mmstick ?

**Comment by jackpot51** [comment]
@superm1 I think that is the long term idea, but the short term is to do what #65 does
