### ISSUE TITLE
firmware-manager uses an insufficient user agent

### ISSUE THREAD

**Issue by hughsie** [pop-os/firmware-manager#67]
Firmware manager seems to download firmware from the LVFS with the user agent `reqwest 0.9.x` which is going to cause problems with some firmware. You need to include the fwupd version in the user agent to be able to download all firmware without an error -- see https://blogs.gnome.org/hughsie/2018/02/16/lvfs-will-block-old-versions-of-fwupd-for-some-firmware/ for details.

The user agent should probably be something like `firmware-manager/0.9 fwupd/1.2.0` for new releases.

**Comment by mmstick** [comment]
Yes, this is the default user agent for a `reqwest::Client`, unless otherwise specified. I think it makes most sense to provide the fwupd version.
