### ISSUE TITLE
Firmware-manage misconfigured on Pop!_OS 19.10

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#75]
The GTK app for firmware-manager is installed on Pop!_OS 19.10 when in fact it should only be accessible from gnome-control-center. This issue is directly related to: https://github.com/pop-os/gnome-control-center/issues/46

**Comment by mmstick** [comment]
It doesn't seem to be a dependency of `gnome-control-center` or `pop-desktop`. it's not installed by `libfirmware-manager`, either.

**Comment by jackpot51** [comment]
gnome-control-center provides girmware-manager on 19.04 right?

**Comment by brs17** [comment]
This seems to have been resolved as recent installs and updates no longer have this issue!
