### ISSUE TITLE
fwupd devices didn't show up

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/firmware-manager#8]

**Comment by mmstick** [comment]
This should be fixed now. Devices were not appearing because the fwupd remote metadata had not been fetched. In the latest commit, the client will fetch the metadata every 2 weeks, but only fetch when there is new metadata on the remote.

**Comment by brs17** [comment]
It appears that the fwupd service is not being started and therefore fwupd devices are not being recognized until restarting the service.

**Comment by brs17** [comment]
@jackpot51 do you have an idea what service should start fwupd?

**Comment by mmstick** [comment]
I think I'll include a simple service file in its own package that `firmware-manager` and `libfirmware-manager` would depend on.
