### ISSUE TITLE
Unable to update device firmware - no update button (20.10)

### ISSUE THREAD

**Issue by pflanzenandi** [pop-os/firmware-manager#89]
![Screenshot-20210102084658-859x457](https://user-images.githubusercontent.com/60046516/103453171-f6a64d80-4cce-11eb-988d-6d2aa7d50809.png)

**Comment by leviport** [comment]
Are you talking about the Unifying Receiver firmware? If an update button is not shown, it most likely means the firmware is already up to date. Expanding the drop-down should show you more version info, so that may be useful.

**Comment by pflanzenandi** [comment]
Hmm, I would assume that only updates are shown in this panel. But Ok

**Comment by leviport** [comment]
Having access to the firmware version and changelog info is useful for some, so we don't really want to hide that. Perhaps there is a better way to indicate that a device is up-to-date though.
