### ISSUE TITLE
Some strings not translatable

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/firmware-manager#97]
The green "Update" button is currently using a [label](https://github.com/pop-os/firmware-manager/blob/c263eea67aa9648eb1e3f8e8be8c1011d52af80c/gtk/src/widgets/mod.rs#L61) with English text instead of a translatable string. The Settings page title ("Firmware") also doesn't seem to be translatable.

![Capture d’écran de 2021-05-18 11-14-37](https://user-images.githubusercontent.com/7199422/118696233-53605b80-b7cb-11eb-981a-1d010db5a836.png)

**Comment by mmstick** [comment]
Fixed the update button, but the title of the panel comes from the desktop file we add in a patch to GNOME Settings: gnome-firmware-panel.desktop
